version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: planning-poker-db
    restart: always
    environment:
      POSTGRES_USER: dockercompose
      POSTGRES_PASSWORD: dockercompose
      POSTGRES_DB: planningpoker
    volumes:
      - postgres_db:/var/lib/postgresql/data
    ports:
      - "5445:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dockercompose -d planningpoker"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_db: